### ISSUE TITLE
Replace deprecated API call

### ISSUE THREAD

**Issue by timhberry** [timhberry/openam-flask-decorator#1]
The decorator uses the 'istokenvalid' API call, which was deprecated in OpenAM 12 and has been removed in OpenAM 13 (see https://backstage.forgerock.com/#!/docs/openam/13/release-notes). The decorator needs to be updated to use the new OpenAM API methods.

**Comment by JoyceZhu** [comment]
Hi @timhberry, could I be assigned to this please?

**Comment by timhberry** [comment]
Hi there! Can you submit a PR? Thanks :)
